ARCHIVE = "https://www.technologyreview.com/supertopic/tr10-archive/"
SEEDED_AT = "2026-09-01T00:00:00"
ADDED_BY = "seed-v1"

BENCHMARKS = [
    {"ticker": "SPY", "name": "S&P 500", "description": "Broad US market benchmark used for excess return."},
    {"ticker": "QQQ", "name": "Nasdaq-100", "description": "Large-cap technology-heavy benchmark."},
    {"ticker": "XLK", "name": "Technology Select Sector", "description": "GICS technology sector ETF."},
    {"ticker": "SOXX", "name": "Semiconductor", "description": "PHLX semiconductor sector ETF."},
    {"ticker": "XBI", "name": "Biotech", "description": "S&P biotech ETF."},
    {"ticker": "TAN", "name": "Solar", "description": "Invesco solar ETF."},
    {"ticker": "ITA", "name": "Aerospace & Defense", "description": "US aerospace and defense ETF."},
    {"ticker": "XLE", "name": "Energy", "description": "Energy select sector ETF."},
    {"ticker": "XLY", "name": "Consumer Discretionary", "description": "Consumer discretionary sector ETF."},
    {"ticker": "GLD", "name": "Gold", "description": "SPDR Gold Shares — the usual listed gold proxy."},
    {"ticker": "USO", "name": "Oil", "description": "United States Oil Fund — WTI crude oil proxy."},
]

YEAR_META = [
    (2001, "verified", "Complete TR10 list for 2001.", ARCHIVE),
    (2002, "none", "No list was published this year.", ARCHIVE),
    (2003, "verified", "Complete TR10 list for 2003.", ARCHIVE),
    (2004, "verified", "Complete TR10 list for 2004.", ARCHIVE),
    (2005, "verified", "Complete TR10 list for 2005.", ARCHIVE),
    (2006, "verified", "Complete TR10 list for 2006.", ARCHIVE),
    (2007, "verified", "Complete TR10 list for 2007.", ARCHIVE),
    (2008, "verified", "Complete TR10 list for 2008.", ARCHIVE),
    (2009, "verified", "Complete TR10 list for 2009.", ARCHIVE),
    (2010, "verified", "Complete TR10 list for 2010.", ARCHIVE),
    (2011, "verified", "Complete TR10 list for 2011.", ARCHIVE),
    (2012, "verified", "Complete TR10 list for 2012.", ARCHIVE),
    (2013, "verified", "Complete TR10 list for 2013.", ARCHIVE),
    (2014, "verified", "Complete TR10 list for 2014.", ARCHIVE),
    (2015, "verified", "Complete TR10 list for 2015.", ARCHIVE),
    (2016, "verified", "Complete TR10 list for 2016.", ARCHIVE),
    (2017, "verified", "Complete TR10 list for 2017.", ARCHIVE),
    (2018, "verified", "Complete TR10 list for 2018.", ARCHIVE),
    (2019, "verified", "Bill Gates guest-curated. Complete TR10 list for 2019.", ARCHIVE),
    (2020, "verified", "Complete TR10 list for 2020.", ARCHIVE),
    (2021, "verified", "20th anniversary list. Complete TR10 list for 2021.", ARCHIVE),
    (2022, "verified", "Complete TR10 list for 2022.", ARCHIVE),
    (2023, "verified", "Complete TR10 list for 2023.", ARCHIVE),
    (2024, "verified", "Complete TR10 list for 2024.", ARCHIVE),
    (2025, "verified", "Complete TR10 list for 2025.", ARCHIVE),
    (2026, "verified", "25th edition. Complete TR10 list for 2026.", "https://www.technologyreview.com/2026/01/12/1130697"),
]

COMPANIES = [
    {"ticker": "NVDA", "name": "NVIDIA", "sector": "Semiconductors", "exchange": "NASDAQ"},
    {"ticker": "GOOGL", "name": "Alphabet", "sector": "Internet", "exchange": "NASDAQ"},
    {"ticker": "MSFT", "name": "Microsoft", "sector": "Software", "exchange": "NASDAQ"},
    {"ticker": "AMZN", "name": "Amazon", "sector": "Internet", "exchange": "NASDAQ"},
    {"ticker": "META", "name": "Meta Platforms", "sector": "Internet", "exchange": "NASDAQ"},
    {"ticker": "AAPL", "name": "Apple", "sector": "Hardware", "exchange": "NASDAQ"},
    {"ticker": "IBM", "name": "IBM", "sector": "IT Services", "exchange": "NYSE"},
    {"ticker": "INTC", "name": "Intel", "sector": "Semiconductors", "exchange": "NASDAQ"},
    {"ticker": "AMD", "name": "Advanced Micro Devices", "sector": "Semiconductors", "exchange": "NASDAQ"},
    {"ticker": "TSM", "name": "TSMC", "sector": "Semiconductors", "exchange": "NYSE", "country": "TW"},
    {"ticker": "AVGO", "name": "Broadcom", "sector": "Semiconductors", "exchange": "NASDAQ"},
    {"ticker": "BIDU", "name": "Baidu", "sector": "Internet", "exchange": "NASDAQ", "country": "CN"},
    {"ticker": "FSLR", "name": "First Solar", "sector": "Solar", "exchange": "NASDAQ"},
    {"ticker": "ENPH", "name": "Enphase Energy", "sector": "Solar", "exchange": "NASDAQ"},
    {"ticker": "SEDG", "name": "SolarEdge", "sector": "Solar", "exchange": "NASDAQ"},
    {"ticker": "CSIQ", "name": "Canadian Solar", "sector": "Solar", "exchange": "NASDAQ", "country": "CA"},
    {"ticker": "GRMN", "name": "Garmin", "sector": "Consumer Electronics", "exchange": "NYSE"},
    {"ticker": "CRSP", "name": "CRISPR Therapeutics", "sector": "Biotech", "exchange": "NASDAQ"},
    {"ticker": "EDIT", "name": "Editas Medicine", "sector": "Biotech", "exchange": "NASDAQ"},
    {"ticker": "NTLA", "name": "Intellia Therapeutics", "sector": "Biotech", "exchange": "NASDAQ"},
    {"ticker": "VRTX", "name": "Vertex Pharmaceuticals", "sector": "Biotech", "exchange": "NASDAQ"},
    {"ticker": "ILMN", "name": "Illumina", "sector": "Life Sciences", "exchange": "NASDAQ"},
    {"ticker": "DE", "name": "Deere & Company", "sector": "Industrials", "exchange": "NYSE"},
    {"ticker": "DDD", "name": "3D Systems", "sector": "Hardware", "exchange": "NYSE"},
    {"ticker": "SSYS", "name": "Stratasys", "sector": "Hardware", "exchange": "NASDAQ"},
    {"ticker": "GH", "name": "Guardant Health", "sector": "Diagnostics", "exchange": "NASDAQ"},
    {"ticker": "EXAS", "name": "Exact Sciences", "sector": "Diagnostics", "exchange": "NASDAQ"},
    {"ticker": "NTRA", "name": "Natera", "sector": "Diagnostics", "exchange": "NASDAQ"},
    {"ticker": "V", "name": "Visa", "sector": "Payments", "exchange": "NYSE"},
    {"ticker": "MA", "name": "Mastercard", "sector": "Payments", "exchange": "NYSE"},
    {"ticker": "TSLA", "name": "Tesla", "sector": "Autos", "exchange": "NASDAQ"},
    {"ticker": "RKLB", "name": "Rocket Lab", "sector": "Aerospace", "exchange": "NASDAQ"},
    {"ticker": "BA", "name": "Boeing", "sector": "Aerospace", "exchange": "NYSE"},
    {"ticker": "LMT", "name": "Lockheed Martin", "sector": "Aerospace", "exchange": "NYSE"},
    {"ticker": "GM", "name": "General Motors", "sector": "Autos", "exchange": "NYSE"},
    {"ticker": "NOW", "name": "ServiceNow", "sector": "Software", "exchange": "NYSE"},
    {"ticker": "CRM", "name": "Salesforce", "sector": "Software", "exchange": "NYSE"},
    {"ticker": "IONQ", "name": "IonQ", "sector": "Quantum", "exchange": "NYSE"},
    {"ticker": "RGTI", "name": "Rigetti Computing", "sector": "Quantum", "exchange": "NASDAQ"},
    {"ticker": "SRPT", "name": "Sarepta Therapeutics", "sector": "Biotech", "exchange": "NASDAQ"},
    {"ticker": "BMRN", "name": "BioMarin", "sector": "Biotech", "exchange": "NASDAQ"},
    {"ticker": "CEG", "name": "Constellation Energy", "sector": "Utilities", "exchange": "NASDAQ"},
    {"ticker": "SMR", "name": "NuScale Power", "sector": "Nuclear", "exchange": "NYSE"},
    {"ticker": "OKLO", "name": "Oklo", "sector": "Nuclear", "exchange": "NYSE"},
    {"ticker": "BWXT", "name": "BWX Technologies", "sector": "Nuclear", "exchange": "NYSE"},
    {"ticker": "BYND", "name": "Beyond Meat", "sector": "Food", "exchange": "NASDAQ"},
    {"ticker": "TSN", "name": "Tyson Foods", "sector": "Food", "exchange": "NYSE"},
    {"ticker": "IRTC", "name": "iRhythm Technologies", "sector": "Medtech", "exchange": "NASDAQ"},
    {"ticker": "COIN", "name": "Coinbase", "sector": "Crypto", "exchange": "NASDAQ"},
    {"ticker": "PYPL", "name": "PayPal", "sector": "Payments", "exchange": "NASDAQ"},
    {"ticker": "XYZ", "name": "Block", "sector": "Payments", "exchange": "NYSE"},
    {"ticker": "MSTR", "name": "Strategy (MicroStrategy)", "sector": "Software", "exchange": "NASDAQ"},
    {"ticker": "ASTS", "name": "AST SpaceMobile", "sector": "Telecom", "exchange": "NASDAQ"},
    {"ticker": "IRDM", "name": "Iridium Communications", "sector": "Telecom", "exchange": "NASDAQ"},
    {"ticker": "MRNA", "name": "Moderna", "sector": "Biotech", "exchange": "NASDAQ"},
    {"ticker": "BNTX", "name": "BioNTech", "sector": "Biotech", "exchange": "NASDAQ", "country": "DE"},
    {"ticker": "PFE", "name": "Pfizer", "sector": "Pharma", "exchange": "NYSE"},
    {"ticker": "NVAX", "name": "Novavax", "sector": "Biotech", "exchange": "NASDAQ"},
    {"ticker": "QS", "name": "QuantumScape", "sector": "Batteries", "exchange": "NYSE"},
    {"ticker": "ALB", "name": "Albemarle", "sector": "Materials", "exchange": "NYSE"},
    {"ticker": "PLUG", "name": "Plug Power", "sector": "Hydrogen", "exchange": "NASDAQ"},
    {"ticker": "BE", "name": "Bloom Energy", "sector": "Hydrogen", "exchange": "NYSE"},
    {"ticker": "APD", "name": "Air Products", "sector": "Chemicals", "exchange": "NYSE"},
    {"ticker": "RXRX", "name": "Recursion Pharmaceuticals", "sector": "Biotech", "exchange": "NASDAQ"},
    {"ticker": "SDGR", "name": "Schrödinger", "sector": "Life Sciences", "exchange": "NASDAQ"},
    {"ticker": "FLNC", "name": "Fluence Energy", "sector": "Energy Storage", "exchange": "NASDAQ"},
    {"ticker": "ADBE", "name": "Adobe", "sector": "Software", "exchange": "NASDAQ"},
    {"ticker": "RIVN", "name": "Rivian", "sector": "Autos", "exchange": "NASDAQ"},
    {"ticker": "LCID", "name": "Lucid Group", "sector": "Autos", "exchange": "NASDAQ"},
    {"ticker": "F", "name": "Ford", "sector": "Autos", "exchange": "NYSE"},
    {"ticker": "LLY", "name": "Eli Lilly", "sector": "Pharma", "exchange": "NYSE"},
    {"ticker": "NVO", "name": "Novo Nordisk", "sector": "Pharma", "exchange": "NYSE", "country": "DK"},
    {"ticker": "AMGN", "name": "Amgen", "sector": "Biotech", "exchange": "NASDAQ"},
    {"ticker": "CARR", "name": "Carrier", "sector": "Industrials", "exchange": "NYSE"},
    {"ticker": "JCI", "name": "Johnson Controls", "sector": "Industrials", "exchange": "NYSE"},
    {"ticker": "TT", "name": "Trane Technologies", "sector": "Industrials", "exchange": "NYSE"},
    {"ticker": "PLTR", "name": "Palantir", "sector": "Software", "exchange": "NASDAQ"},
    {"ticker": "GTLB", "name": "GitLab", "sector": "Software", "exchange": "NASDAQ"},
    {"ticker": "EQIX", "name": "Equinix", "sector": "Data Centers", "exchange": "NASDAQ"},
    {"ticker": "DLR", "name": "Digital Realty", "sector": "Data Centers", "exchange": "NYSE"},
    {"ticker": "VRT", "name": "Vertiv", "sector": "Electrical Equipment", "exchange": "NYSE"},
    {"ticker": "SNAP", "name": "Snap", "sector": "Internet", "exchange": "NYSE"},
    {"ticker": "NOC", "name": "Northrop Grumman", "sector": "Aerospace", "exchange": "NYSE"},
    {"ticker": "GEV", "name": "GE Vernova", "sector": "Energy Equipment", "exchange": "NYSE"},
    {"ticker": "VST", "name": "Vistra", "sector": "Utilities", "exchange": "NYSE"},
    {"ticker": "REGN", "name": "Regeneron", "sector": "Biotech", "exchange": "NASDAQ"},
    {"ticker": "RUN", "name": "Sunrun", "sector": "Solar", "exchange": "NASDAQ"},
    {"ticker": "HON", "name": "Honeywell", "sector": "Industrials", "exchange": "NASDAQ"},
    {"ticker": "WORK", "name": "Slack Technologies", "sector": "Software", "exchange": "NYSE",
     "delisted_date": "2021-07-21", "delisted_reason": "Acquired by Salesforce"},
    {"ticker": "FIT", "name": "Fitbit", "sector": "Consumer Electronics", "exchange": "NYSE",
     "delisted_date": "2021-01-14", "delisted_reason": "Acquired by Alphabet"},
    {"ticker": "MBLY", "name": "Mobileye", "sector": "Autos", "exchange": "NASDAQ"},
    {"ticker": "CRWD", "name": "CrowdStrike", "sector": "Cybersecurity", "exchange": "NASDAQ"},
    {"ticker": "OKTA", "name": "Okta", "sector": "Cybersecurity", "exchange": "NASDAQ"},
    {"ticker": "ANET", "name": "Arista Networks", "sector": "Networking", "exchange": "NYSE"},
]

TECHNOLOGIES = [
    # 2001
    {"year": 2001, "name": "Brain-Machine Interface", "category": "biotech", "status": "verified", "desc": "Early neural interfaces connecting brains to machines."},
    {"year": 2001, "name": "Flexible Transistors", "category": "hardware", "status": "verified", "desc": "Transistors on flexible substrates for new form factors."},
    {"year": 2001, "name": "Data Mining", "category": "ai", "status": "verified", "desc": "Extracting patterns from large datasets at commercial scale."},
    {"year": 2001, "name": "Digital Rights Management", "category": "consumer", "status": "verified", "desc": "Technical controls for digital media distribution."},
    {"year": 2001, "name": "Biometrics", "category": "hardware", "status": "verified", "desc": "Identity from fingerprints, faces, and other biological signals."},
    {"year": 2001, "name": "Natural Language Processing", "category": "ai", "status": "verified", "desc": "Machines reading and generating human language."},
    {"year": 2001, "name": "Microphotonics", "category": "hardware", "status": "verified", "desc": "Optical components at chip scale."},
    {"year": 2001, "name": "Untangling Code", "category": "ai", "status": "verified", "desc": "Tools for understanding and restructuring complex software."},
    {"year": 2001, "name": "Robot Design", "category": "hardware", "status": "verified", "desc": "New approaches to designing practical robots."},
    {"year": 2001, "name": "Microfluidics", "category": "biotech", "status": "verified", "desc": "Lab-on-a-chip fluid handling."},
    # 2003
    {"year": 2003, "name": "Wireless Sensor Networks", "category": "hardware", "status": "verified", "desc": "Distributed sensing over wireless mesh networks."},
    {"year": 2003, "name": "Injectable Tissue Engineering", "category": "biotech", "status": "verified", "desc": "Injectable materials that help tissue regenerate."},
    {"year": 2003, "name": "Nano Solar Cells", "category": "energy", "status": "verified", "desc": "Nanomaterials aimed at cheaper photovoltaics."},
    {"year": 2003, "name": "Mechatronics", "category": "hardware", "status": "verified", "desc": "Tight integration of mechanics, electronics, and control."},
    {"year": 2003, "name": "Grid Computing", "category": "ai", "status": "verified", "desc": "Shared computing across institutional boundaries."},
    {"year": 2003, "name": "Molecular Imaging", "category": "biotech", "status": "verified", "desc": "Imaging biochemical processes in living systems."},
    {"year": 2003, "name": "Nanoimprint Lithography", "category": "hardware", "status": "verified", "desc": "Stamping nanoscale patterns as an alternative to photolithography."},
    {"year": 2003, "name": "Software Assurance", "category": "ai", "status": "verified", "desc": "Methods to prove software behaves as specified."},
    {"year": 2003, "name": "Glycomics", "category": "biotech", "status": "verified", "desc": "Systematic study of sugars in biology."},
    {"year": 2003, "name": "Quantum Cryptography", "category": "hardware", "status": "verified", "desc": "Key distribution using quantum states."},
    # 2004
    {"year": 2004, "name": "Universal Translation", "category": "ai", "status": "verified", "desc": "Machine translation toward language-universal coverage."},
    {"year": 2004, "name": "Synthetic Biology", "category": "biotech", "status": "verified", "desc": "Engineering living systems from standardized parts."},
    {"year": 2004, "name": "Nanowires", "category": "hardware", "status": "verified", "desc": "One-dimensional conductors for electronics and sensing."},
    {"year": 2004, "name": "T-Rays", "category": "hardware", "status": "verified", "desc": "Terahertz imaging between microwave and infrared."},
    {"year": 2004, "name": "Distributed Storage", "category": "ai", "status": "verified", "desc": "Data stored across many machines rather than one vault."},
    {"year": 2004, "name": "RNAi Interference", "category": "biotech", "status": "verified", "desc": "Silencing genes with RNA interference."},
    {"year": 2004, "name": "Power Grid Control", "category": "energy", "status": "verified", "desc": "Software and sensors for a more controllable grid."},
    {"year": 2004, "name": "Microfluidic Optical Fibers", "category": "hardware", "status": "verified", "desc": "Fibers that combine light and fluid channels."},
    {"year": 2004, "name": "Bayesian Machine Learning", "category": "ai", "status": "verified", "desc": "Probabilistic models that quantify uncertainty."},
    {"year": 2004, "name": "Personal Genomics", "category": "biotech", "status": "verified", "desc": "Cheap enough genomes to be individual medical records."},
    # 2005
    {"year": 2005, "name": "Airborne Networks", "category": "hardware", "status": "verified", "desc": "Ad-hoc networks among aircraft and other flying nodes."},
    {"year": 2005, "name": "Quantum Wires", "category": "hardware", "status": "verified", "desc": "One-dimensional conductors with quantum behavior."},
    {"year": 2005, "name": "Silicon Photonics", "category": "hardware", "status": "verified", "desc": "Optical communication built in silicon chip processes."},
    {"year": 2005, "name": "Metabolomics", "category": "biotech", "status": "verified", "desc": "Systematic measurement of metabolites in cells and tissues."},
    {"year": 2005, "name": "Magnetic-Resonance Force Microscopy", "category": "hardware", "status": "verified", "desc": "Imaging at molecular scale with magnetic resonance."},
    {"year": 2005, "name": "Universal Memory", "category": "hardware", "status": "verified", "desc": "Memory that aims to replace DRAM, flash, and hard disks."},
    {"year": 2005, "name": "Bacterial Factories", "category": "biotech", "status": "verified", "desc": "Engineered microbes as chemical production plants."},
    {"year": 2005, "name": "Enviromatics", "category": "energy", "status": "verified", "desc": "Informatics for environmental monitoring and prediction."},
    {"year": 2005, "name": "Cell-Phone Viruses", "category": "consumer", "status": "verified", "desc": "Malware spreading across mobile handsets."},
    {"year": 2005, "name": "Biomechatronics", "category": "biotech", "status": "verified", "desc": "Machines integrated with the human neuromuscular system."},
    # 2006
    {"year": 2006, "name": "Nanomedicine", "category": "biotech", "status": "verified", "desc": "Medical devices and drugs at the nanoscale."},
    {"year": 2006, "name": "Nanobiomechanics", "category": "biotech", "status": "verified", "desc": "Measuring mechanical forces inside cells."},
    {"year": 2006, "name": "Epigenetics", "category": "biotech", "status": "verified", "desc": "Heritable gene-activity changes without rewriting DNA sequence."},
    {"year": 2006, "name": "Comparative Interactomics", "category": "biotech", "status": "verified", "desc": "Comparing protein-interaction networks across species."},
    {"year": 2006, "name": "Diffusion Tensor Imaging", "category": "biotech", "status": "verified", "desc": "MRI that maps white-matter tracts in the brain."},
    {"year": 2006, "name": "Cognitive Radio", "category": "hardware", "status": "verified", "desc": "Radios that find and use spare spectrum dynamically."},
    {"year": 2006, "name": "Pervasive Wireless", "category": "hardware", "status": "verified", "desc": "Always-on wireless coverage as a default layer."},
    {"year": 2006, "name": "Universal Authentication", "category": "consumer", "status": "verified", "desc": "One identity system across services and devices."},
    {"year": 2006, "name": "Nuclear Reprogramming", "category": "biotech", "status": "verified", "desc": "Resetting adult cells toward an embryonic-like state."},
    {"year": 2006, "name": "Stretchable Silicon", "category": "hardware", "status": "verified", "desc": "Electronics that bend and stretch with the body or device."},
    # 2007
    {"year": 2007, "name": "Peering into Video's Future", "category": "consumer", "status": "verified", "desc": "Internet video moving from clips to a primary medium."},
    {"year": 2007, "name": "Nanocharging Solar", "category": "energy", "status": "verified", "desc": "Nanomaterials to raise solar conversion efficiency.", "benchmark": "TAN"},
    {"year": 2007, "name": "Invisible Revolution", "category": "hardware", "status": "verified", "desc": "Metamaterials that steer light around objects."},
    {"year": 2007, "name": "Personalized Medical Monitors", "category": "biotech", "status": "verified", "desc": "Continuous, personal diagnostic sensors."},
    {"year": 2007, "name": "Single-Cell Analysis", "category": "biotech", "status": "verified", "desc": "Measuring biology one cell at a time."},
    {"year": 2007, "name": "A New Focus for Light", "category": "hardware", "status": "verified", "desc": "Lenses and optics that beat old diffraction limits."},
    {"year": 2007, "name": "Neuron Control", "category": "biotech", "status": "verified", "desc": "Tools to switch neurons on and off."},
    {"year": 2007, "name": "Nanohealing", "category": "biotech", "status": "verified", "desc": "Nanomaterials that stop bleeding or repair tissue."},
    {"year": 2007, "name": "Digital Imaging, Reimagined", "category": "hardware", "status": "verified", "desc": "New camera architectures beyond the conventional sensor."},
    {"year": 2007, "name": "Augmented Reality", "category": "consumer", "status": "verified", "desc": "Graphics registered onto the real world."},
    # 2008
    {"year": 2008, "name": "Modeling Surprise", "category": "ai", "status": "verified", "desc": "Systems that detect and reason about unexpected events."},
    {"year": 2008, "name": "Probabilistic Chips", "category": "hardware", "status": "verified", "desc": "Processors that trade a little error for a lot of efficiency.", "benchmark": "SOXX"},
    {"year": 2008, "name": "NanoRadio", "category": "hardware", "status": "verified", "desc": "Radios built from nanoscale mechanical resonators."},
    {"year": 2008, "name": "Wireless Power", "category": "hardware", "status": "verified", "desc": "Transferring energy without a cable."},
    {"year": 2008, "name": "Atomic Magnetometers", "category": "hardware", "status": "verified", "desc": "Tiny sensors of magnetic fields at atomic sensitivity."},
    {"year": 2008, "name": "Offline Web Applications", "category": "consumer", "status": "verified", "desc": "Web apps that keep working without a live connection."},
    {"year": 2008, "name": "Graphene Transistors", "category": "hardware", "status": "verified", "desc": "Carbon-sheet electronics as a silicon alternative.", "benchmark": "SOXX"},
    {"year": 2008, "name": "Connectomics", "category": "biotech", "status": "verified", "desc": "Mapping every connection in a nervous system."},
    {"year": 2008, "name": "Reality Mining", "category": "ai", "status": "verified", "desc": "Inferring social behavior from phone and sensor traces."},
    {"year": 2008, "name": "Cellulolytic Enzymes", "category": "energy", "status": "verified", "desc": "Enzymes that break cellulose into fuel sugars."},
    # 2009
    {"year": 2009, "name": "Intelligent Software Assistant", "category": "ai", "status": "verified", "desc": "Software that acts on a user's behalf from natural language."},
    {"year": 2009, "name": "$100 Genome", "category": "biotech", "status": "verified", "desc": "Sequencing cheap enough for routine medicine.", "benchmark": "XBI"},
    {"year": 2009, "name": "Racetrack Memory", "category": "hardware", "status": "verified", "desc": "IBM's dense magnetic-domain memory concept."},
    {"year": 2009, "name": "Biological Machines", "category": "biotech", "status": "verified", "desc": "Living systems engineered as machines."},
    {"year": 2009, "name": "Paper Diagnostics", "category": "biotech", "status": "verified", "desc": "Medical tests printed on paper for cheap, distributed use."},
    {"year": 2009, "name": "Liquid Battery", "category": "energy", "status": "verified", "desc": "Flowing-electrolyte storage for the grid.", "benchmark": "XLE"},
    {"year": 2009, "name": "Traveling-Wave Reactor", "category": "energy", "status": "verified", "desc": "A reactor design that burns depleted uranium more completely.", "benchmark": "XLE"},
    {"year": 2009, "name": "Nanopiezoelectronics", "category": "hardware", "status": "verified", "desc": "Nanowires that generate current from mechanical strain."},
    {"year": 2009, "name": "HashCache", "category": "ai", "status": "verified", "desc": "A caching scheme for cheap, large-scale web storage."},
    {"year": 2009, "name": "Software-Defined Networking", "category": "hardware", "status": "verified", "desc": "Network control pulled out of hardware into software."},
    # 2010
    {"year": 2010, "name": "Real-Time Search", "category": "ai", "status": "verified", "desc": "Search that includes what was just posted."},
    {"year": 2010, "name": "Mobile 3-D", "category": "consumer", "status": "verified", "desc": "Stereoscopic 3-D on phones and handhelds."},
    {"year": 2010, "name": "Engineered Stem Cells", "category": "biotech", "status": "verified", "desc": "Stem cells made more controllable for therapy.", "benchmark": "XBI"},
    {"year": 2010, "name": "Solar Fuel", "category": "energy", "status": "verified", "desc": "Using sunlight to make chemical fuels.", "benchmark": "XLE"},
    {"year": 2010, "name": "Light-Trapping Photovoltaics", "category": "energy", "status": "verified", "desc": "Cell textures that trap more of the incoming light.", "benchmark": "TAN"},
    {"year": 2010, "name": "Social TV", "category": "consumer", "status": "verified", "desc": "Television designed around chatting and sharing."},
    {"year": 2010, "name": "Green Concrete", "category": "energy", "status": "verified", "desc": "Cement and concrete with a much smaller carbon footprint."},
    {"year": 2010, "name": "Implantable Electronics", "category": "biotech", "status": "verified", "desc": "Electronics meant to live inside the body."},
    {"year": 2010, "name": "Dual-Action Antibodies", "category": "biotech", "status": "verified", "desc": "Antibodies engineered to bind two targets at once.", "benchmark": "XBI"},
    {"year": 2010, "name": "Cloud Programming", "category": "ai", "status": "verified", "desc": "Languages and tools built for cloud-scale software."},
    # 2011
    {"year": 2011, "name": "Social Indexing", "category": "ai", "status": "verified", "desc": "Ranking information using a person's social graph."},
    {"year": 2011, "name": "Smart Transformers", "category": "energy", "status": "verified", "desc": "Grid transformers that sense and switch in real time."},
    {"year": 2011, "name": "Gestural Interfaces", "category": "consumer", "status": "verified", "desc": "Computers controlled by hand and body motion."},
    {"year": 2011, "name": "Cancer Genomics", "category": "biotech", "status": "verified", "desc": "Sequencing tumors to choose treatment.", "benchmark": "XBI"},
    {"year": 2011, "name": "Solid-State Batteries", "category": "energy", "status": "verified", "desc": "Batteries that replace liquid electrolyte with solid material.", "benchmark": "XLE"},
    {"year": 2011, "name": "Homomorphic Encryption", "category": "ai", "status": "verified", "desc": "Computing on data without decrypting it."},
    {"year": 2011, "name": "Cloud Streaming", "category": "consumer", "status": "verified", "desc": "Running software in the cloud and streaming the result."},
    {"year": 2011, "name": "Crash-Proof Code", "category": "ai", "status": "verified", "desc": "Methods that make software fail less often."},
    {"year": 2011, "name": "Separating Chromosomes", "category": "biotech", "status": "verified", "desc": "Reading maternal and paternal chromosomes apart."},
    {"year": 2011, "name": "Synthetic Cells", "category": "biotech", "status": "verified", "desc": "Cells whose genomes are written rather than inherited."},
    # 2012
    {"year": 2012, "name": "Egg Stem Cells", "category": "biotech", "status": "verified", "desc": "Stem cells that can become human eggs."},
    {"year": 2012, "name": "Ultra-Efficient Solar", "category": "energy", "status": "verified", "desc": "Photovoltaics pushing conversion efficiency higher.", "benchmark": "TAN"},
    {"year": 2012, "name": "Light-Field Photography", "category": "consumer", "status": "verified", "desc": "Cameras that capture a scene to refocus later."},
    {"year": 2012, "name": "Solar Microgrids", "category": "energy", "status": "verified", "desc": "Local solar-plus-storage grids, especially off the main grid.", "benchmark": "TAN"},
    {"year": 2012, "name": "3-D Transistors", "category": "hardware", "status": "verified", "desc": "FinFET-style transistors leaving the flat plane.", "benchmark": "SOXX"},
    {"year": 2012, "name": "A Faster Fourier Transform", "category": "ai", "status": "verified", "desc": "A faster algorithm for a core signal-processing transform."},
    {"year": 2012, "name": "Nanopore Sequencing", "category": "biotech", "status": "verified", "desc": "Reading DNA as it threads through a nanopore.", "benchmark": "XBI"},
    {"year": 2012, "name": "Crowdfunding", "category": "consumer", "status": "verified", "desc": "Raising capital from large numbers of small backers."},
    {"year": 2012, "name": "High-Speed Materials Discovery", "category": "hardware", "status": "verified", "desc": "Combinatorial methods to find new materials faster."},
    {"year": 2012, "name": "Facebook's Timeline", "category": "consumer", "status": "verified", "desc": "A chronological social profile as a product pattern."},
    # 2013
    {"year": 2013, "name": "Deep Learning", "category": "ai", "status": "verified", "desc": "Multi-layer neural nets becoming practical for perception and speech.", "benchmark": "SOXX"},
    {"year": 2013, "name": "Ultra-Efficient Solar Power", "category": "energy", "status": "verified", "desc": "Higher-efficiency photovoltaics approaching cost competitiveness.", "benchmark": "TAN"},
    {"year": 2013, "name": "Big Data from Cheap Phones", "category": "ai", "status": "verified", "desc": "Mobile devices as a planetary sensor network."},
    {"year": 2013, "name": "Temporary Social Media", "category": "consumer", "status": "verified", "desc": "Ephemeral posts as a product pattern."},
    {"year": 2013, "name": "Smart Watches", "category": "consumer", "status": "verified", "desc": "Wrist computers leaving niche gadget status."},
    {"year": 2013, "name": "Memory Implants", "category": "biotech", "status": "verified", "desc": "Neural prostheses aimed at restoring memory."},
    {"year": 2013, "name": "Baxter: The Blue-Collar Robot", "category": "hardware", "status": "verified", "desc": "A factory robot designed to work beside people."},
    {"year": 2013, "name": "Additive Manufacturing", "category": "hardware", "status": "verified", "desc": "3-D printing moving from prototypes toward production parts."},
    {"year": 2013, "name": "Prenatal DNA Sequencing", "category": "biotech", "status": "verified", "desc": "Fetal genomes read from the mother's blood.", "benchmark": "XBI"},
    {"year": 2013, "name": "Supergrids", "category": "energy", "status": "verified", "desc": "Long-distance, high-capacity grids for renewable power."},
    # 2014
    {"year": 2014, "name": "Agricultural Drones", "category": "industrial", "status": "verified", "desc": "UAVs for crop monitoring and spraying."},
    {"year": 2014, "name": "Ultraprivate Smartphones", "category": "consumer", "status": "verified", "desc": "Handsets designed around default privacy."},
    {"year": 2014, "name": "Brain Mapping", "category": "biotech", "status": "verified", "desc": "Large-scale maps of neural connections.", "benchmark": "XBI"},
    {"year": 2014, "name": "Neuromorphic Chips", "category": "hardware", "status": "verified", "desc": "Processors that mimic neural architecture.", "benchmark": "SOXX"},
    {"year": 2014, "name": "Genome Editing", "category": "biotech", "status": "verified", "desc": "CRISPR-class tools to rewrite DNA.", "benchmark": "XBI"},
    {"year": 2014, "name": "Microscale 3-D Printing", "category": "hardware", "status": "verified", "desc": "Additive manufacturing at very small feature sizes."},
    {"year": 2014, "name": "Mobile Collaboration", "category": "consumer", "status": "verified", "desc": "Work tools built for phones rather than desks."},
    {"year": 2014, "name": "Oculus Rift", "category": "consumer", "status": "verified", "desc": "Consumer VR headset that reset expectations for virtual reality."},
    {"year": 2014, "name": "Agile Robots", "category": "hardware", "status": "verified", "desc": "Robots that balance and move in unstructured spaces."},
    {"year": 2014, "name": "Smart Wind and Solar Power", "category": "energy", "status": "verified", "desc": "Forecasting and controls that make renewables dispatchable.", "benchmark": "TAN"},
    # 2015
    {"year": 2015, "name": "Magic Leap", "category": "consumer", "status": "verified", "desc": "Optical see-through AR as a computing platform."},
    {"year": 2015, "name": "Nano-Architecture", "category": "hardware", "status": "verified", "desc": "Materials whose properties come from nanoscale geometry."},
    {"year": 2015, "name": "Car-to-Car Communication", "category": "industrial", "status": "verified", "desc": "Vehicles sharing state to reduce collisions."},
    {"year": 2015, "name": "Project Loon", "category": "consumer", "status": "verified", "desc": "Balloon-based internet for uncovered regions."},
    {"year": 2015, "name": "Liquid Biopsy", "category": "biotech", "status": "verified", "desc": "Cancer detection from blood rather than tissue.", "benchmark": "XBI"},
    {"year": 2015, "name": "Megascale Desalination", "category": "energy", "status": "verified", "desc": "Very large plants making seawater a municipal supply."},
    {"year": 2015, "name": "Apple Pay", "category": "consumer", "status": "verified", "desc": "NFC payments reaching default consumer behavior."},
    {"year": 2015, "name": "Brain Organoids", "category": "biotech", "status": "verified", "desc": "Lab-grown mini-brains for research.", "benchmark": "XBI"},
    {"year": 2015, "name": "Supercharged Photosynthesis", "category": "energy", "status": "verified", "desc": "Rewiring plants to fix carbon more efficiently."},
    {"year": 2015, "name": "Internet of DNA", "category": "biotech", "status": "verified", "desc": "Shared genomic databases across labs and clinics.", "benchmark": "XBI"},
    # 2016
    {"year": 2016, "name": "Immune Engineering", "category": "biotech", "status": "verified", "desc": "Reprogramming immune cells as living drugs.", "benchmark": "XBI"},
    {"year": 2016, "name": "Precise Gene Editing in Plants", "category": "biotech", "status": "verified", "desc": "CRISPR applied to crops.", "benchmark": "XBI"},
    {"year": 2016, "name": "Conversational Interfaces", "category": "ai", "status": "verified", "desc": "Voice assistants as a primary computer interface.", "benchmark": "XLK"},
    {"year": 2016, "name": "Reusable Rockets", "category": "space", "status": "verified", "desc": "Orbital-class boosters that land and fly again.", "benchmark": "ITA"},
    {"year": 2016, "name": "Robots That Teach Each Other", "category": "ai", "status": "verified", "desc": "Skill transfer across robot fleets."},
    {"year": 2016, "name": "DNA App Store", "category": "biotech", "status": "verified", "desc": "On-demand genetic constructs as a service."},
    {"year": 2016, "name": "SolarCity's Gigafactory", "category": "energy", "status": "verified", "desc": "US-scale solar manufacturing bet.", "benchmark": "TAN"},
    {"year": 2016, "name": "Slack", "category": "consumer", "status": "verified", "desc": "Workplace chat displacing email threads.", "benchmark": "XLK"},
    {"year": 2016, "name": "Tesla Autopilot", "category": "industrial", "status": "verified", "desc": "Highway driver assistance as a consumer product.", "benchmark": "XLY"},
    {"year": 2016, "name": "Power from the Air", "category": "hardware", "status": "verified", "desc": "Harvesting energy from ambient radio waves."},
    # 2017
    {"year": 2017, "name": "Reversing Paralysis", "category": "biotech", "status": "verified", "desc": "Neural interfaces restoring movement.", "benchmark": "XBI"},
    {"year": 2017, "name": "Self-Driving Trucks", "category": "industrial", "status": "verified", "desc": "Autonomy first on highways, not city streets.", "benchmark": "XLY"},
    {"year": 2017, "name": "Paying with Your Face", "category": "consumer", "status": "verified", "desc": "Face as authentication for payments."},
    {"year": 2017, "name": "Practical Quantum Computers", "category": "hardware", "status": "verified", "desc": "Machines leaving pure lab demos toward usable qubits.", "benchmark": "XLK"},
    {"year": 2017, "name": "The 360-Degree Selfie", "category": "consumer", "status": "verified", "desc": "Consumer capture of full spherical video."},
    {"year": 2017, "name": "Hot Solar Cells", "category": "energy", "status": "verified", "desc": "Harvesting waste heat to raise solar efficiency.", "benchmark": "TAN"},
    {"year": 2017, "name": "Gene Therapy 2.0", "category": "biotech", "status": "verified", "desc": "Approved gene therapies after decades of false starts.", "benchmark": "XBI"},
    {"year": 2017, "name": "The Cell Atlas", "category": "biotech", "status": "verified", "desc": "A reference map of human cell types.", "benchmark": "XBI"},
    {"year": 2017, "name": "Botnets of Things", "category": "hardware", "status": "verified", "desc": "IoT devices as an attack surface."},
    {"year": 2017, "name": "Reinforcement Learning", "category": "ai", "status": "verified", "desc": "Agents that learn from reward rather than labels.", "benchmark": "XLK"},
    # 2018
    {"year": 2018, "name": "3-D Metal Printing", "category": "hardware", "status": "verified", "desc": "Additive manufacturing of production metal parts."},
    {"year": 2018, "name": "Artificial Embryos", "category": "biotech", "status": "verified", "desc": "Embryo-like structures grown from stem cells.", "benchmark": "XBI"},
    {"year": 2018, "name": "Sensing City", "category": "industrial", "status": "verified", "desc": "Urban infrastructure instrumented with sensors."},
    {"year": 2018, "name": "AI for Everybody", "category": "ai", "status": "verified", "desc": "Cloud APIs putting machine learning in ordinary software.", "benchmark": "XLK"},
    {"year": 2018, "name": "Dueling Neural Networks", "category": "ai", "status": "verified", "desc": "Generative adversarial networks leaving research papers.", "benchmark": "XLK"},
    {"year": 2018, "name": "Babel-Fish Earbuds", "category": "consumer", "status": "verified", "desc": "Near real-time spoken translation in an earpiece."},
    {"year": 2018, "name": "Zero-Carbon Natural Gas", "category": "energy", "status": "verified", "desc": "Gas plants that capture their carbon.", "benchmark": "XLE"},
    {"year": 2018, "name": "Perfect Online Privacy", "category": "consumer", "status": "verified", "desc": "Cryptographic tools aiming at default private communication."},
    {"year": 2018, "name": "Genetic Fortune-Telling", "category": "biotech", "status": "verified", "desc": "Polygenic scores claiming to predict traits and disease.", "benchmark": "XBI"},
    {"year": 2018, "name": "Materials' Quantum Leap", "category": "hardware", "status": "verified", "desc": "Quantum methods to discover materials."},
    # 2019
    {"year": 2019, "name": "Robot Dexterity", "category": "hardware", "status": "verified", "desc": "Hands that manipulate messy, varied objects."},
    {"year": 2019, "name": "New-Wave Nuclear Power", "category": "energy", "status": "verified", "desc": "Smaller, safer reactor designs aiming at cheaper nuclear.", "benchmark": "XLE"},
    {"year": 2019, "name": "Predicting Preemies", "category": "biotech", "status": "verified", "desc": "Tests to forecast preterm birth.", "benchmark": "XBI"},
    {"year": 2019, "name": "Gut Probe in a Pill", "category": "biotech", "status": "verified", "desc": "Ingestible diagnostics for the GI tract.", "benchmark": "XBI"},
    {"year": 2019, "name": "Custom Cancer Vaccines", "category": "biotech", "status": "verified", "desc": "Vaccines tailored to a patient's tumor mutations.", "benchmark": "XBI"},
    {"year": 2019, "name": "The Cow-Free Burger", "category": "consumer", "status": "verified", "desc": "Plant or cultured protein sold as a burger.", "benchmark": "XLY"},
    {"year": 2019, "name": "Carbon Dioxide Catcher", "category": "energy", "status": "verified", "desc": "Machines that pull CO2 from air.", "benchmark": "XLE"},
    {"year": 2019, "name": "An ECG on Your Wrist", "category": "consumer", "status": "verified", "desc": "Medical-grade heart traces from a watch."},
    {"year": 2019, "name": "Sanitation Without Sewers", "category": "industrial", "status": "verified", "desc": "Toilet systems that do not need municipal pipes."},
    {"year": 2019, "name": "Smooth-Talking AI Assistants", "category": "ai", "status": "verified", "desc": "Voice agents that hold a natural conversation.", "benchmark": "XLK"},
    # 2020
    {"year": 2020, "name": "Unhackable Internet", "category": "hardware", "status": "verified", "desc": "Quantum and cryptographic paths toward harder-to-tap networks."},
    {"year": 2020, "name": "Hyper-Personalized Medicine", "category": "biotech", "status": "verified", "desc": "Treatments designed around a single patient.", "benchmark": "XBI"},
    {"year": 2020, "name": "Digital Money", "category": "consumer", "status": "verified", "desc": "Crypto and digital cash moving into the financial mainstream."},
    {"year": 2020, "name": "Anti-Aging Drugs", "category": "biotech", "status": "verified", "desc": "Compounds aimed at aging mechanisms rather than one disease.", "benchmark": "XBI"},
    {"year": 2020, "name": "AI-Discovered Molecules", "category": "biotech", "status": "verified", "desc": "Machine learning proposing drug candidates.", "benchmark": "XBI"},
    {"year": 2020, "name": "Satellite Mega-Constellations", "category": "space", "status": "verified", "desc": "Hundreds to thousands of small satellites for global coverage.", "benchmark": "ITA"},
    {"year": 2020, "name": "Quantum Supremacy", "category": "hardware", "status": "verified", "desc": "A quantum device beating classical computers on a contrived task.", "benchmark": "XLK"},
    {"year": 2020, "name": "Tiny AI", "category": "ai", "status": "verified", "desc": "Neural nets small enough to run on phones and microcontrollers.", "benchmark": "SOXX"},
    {"year": 2020, "name": "Differential Privacy", "category": "ai", "status": "verified", "desc": "Math that lets datasets be used without exposing individuals."},
    {"year": 2020, "name": "Climate-Change Attribution", "category": "energy", "status": "verified", "desc": "Science that ties extreme weather to climate change in near-real time."},
    # 2021
    {"year": 2021, "name": "Messenger RNA Vaccines", "category": "biotech", "status": "verified", "desc": "mRNA as a rapid vaccine platform after COVID-19.", "benchmark": "XBI"},
    {"year": 2021, "name": "GPT-3", "category": "ai", "status": "verified", "desc": "Large language models becoming a general-purpose interface.", "benchmark": "XLK"},
    {"year": 2021, "name": "TikTok Recommendation Algorithms", "category": "ai", "status": "verified", "desc": "For-you feeds that outperform social graphs.", "benchmark": "XLK"},
    {"year": 2021, "name": "Lithium-Metal Batteries", "category": "energy", "status": "verified", "desc": "Anodes that raise energy density beyond graphite.", "benchmark": "XLE"},
    {"year": 2021, "name": "Data Trusts", "category": "consumer", "status": "verified", "desc": "Legal wrappers for pooling data without giving it away."},
    {"year": 2021, "name": "Green Hydrogen", "category": "energy", "status": "verified", "desc": "Hydrogen from renewables as an industrial fuel.", "benchmark": "XLE"},
    {"year": 2021, "name": "Digital Contact Tracing", "category": "consumer", "status": "verified", "desc": "Phone-based exposure notification."},
    {"year": 2021, "name": "Hyper-Accurate Positioning", "category": "hardware", "status": "verified", "desc": "Location precision beyond classic GPS."},
    {"year": 2021, "name": "Remote Everything", "category": "consumer", "status": "verified", "desc": "Work, medicine, and school designed to happen off-site.", "benchmark": "XLK"},
    {"year": 2021, "name": "Multi-Skilled AI", "category": "ai", "status": "verified", "desc": "Models that combine language, vision, and action.", "benchmark": "XLK"},
    # 2022
    {"year": 2022, "name": "COVID Pill", "category": "biotech", "status": "verified", "desc": "Oral antivirals for SARS-CoV-2.", "benchmark": "XBI"},
    {"year": 2022, "name": "Practical Fusion Reactors", "category": "energy", "status": "verified", "desc": "Private fusion moving from physics demo toward plants.", "benchmark": "XLE"},
    {"year": 2022, "name": "A Proof of Stake", "category": "consumer", "status": "verified", "desc": "Ethereum-class networks dropping proof of work."},
    {"year": 2022, "name": "Long-Lasting Grid Batteries", "category": "energy", "status": "verified", "desc": "Storage that holds power for many hours, not minutes.", "benchmark": "XLE"},
    {"year": 2022, "name": "AI for Protein Folding", "category": "biotech", "status": "verified", "desc": "Structure prediction as a default biology tool.", "benchmark": "XBI"},
    {"year": 2022, "name": "Malaria Vaccine", "category": "biotech", "status": "verified", "desc": "A vaccine with real-world impact against malaria.", "benchmark": "XBI"},
    {"year": 2022, "name": "Synthetic Data for AI", "category": "ai", "status": "verified", "desc": "Fake data used to train models when real data is scarce.", "benchmark": "XLK"},
    {"year": 2022, "name": "Carbon Removal Factory", "category": "energy", "status": "verified", "desc": "Industrial plants whose product is negative emissions.", "benchmark": "XLE"},
    {"year": 2022, "name": "The End of Passwords", "category": "consumer", "status": "verified", "desc": "Passkeys and device-bound credentials replacing passwords."},
    {"year": 2022, "name": "COVID Variant Tracking", "category": "biotech", "status": "verified", "desc": "Genomic surveillance of viral evolution.", "benchmark": "XBI"},
    # 2023
    {"year": 2023, "name": "CRISPR for High Cholesterol", "category": "biotech", "status": "verified", "benchmark": "XBI",
     "desc": "Over the past decade, the gene-editing tool CRISPR has rapidly evolved from the lab to the clinic. It started with experimental treatments for rare genetic disorders and has recently expanded into clinical trials for common conditions, including high cholesterol. New forms of CRISPR could take things further still."},
    {"year": 2023, "name": "AI That Makes Images", "category": "ai", "status": "verified", "desc": "Diffusion models turning text into pictures.", "benchmark": "XLK"},
    {"year": 2023, "name": "A Chip Design That Changes Everything", "category": "hardware", "status": "verified", "desc": "A shift in how high-performance chips are architected.", "benchmark": "SOXX"},
    {"year": 2023, "name": "Mass-Market Military Drones", "category": "industrial", "status": "verified", "desc": "Cheap drones changing the economics of conflict.", "benchmark": "ITA"},
    {"year": 2023, "name": "Abortion Pills via Telemedicine", "category": "biotech", "status": "verified", "desc": "Medication abortion delivered remotely."},
    {"year": 2023, "name": "Organs on Demand", "category": "biotech", "status": "verified", "desc": "Lab-grown or xenotransplant organs.", "benchmark": "XBI"},
    {"year": 2023, "name": "The Inevitable EV", "category": "energy", "status": "verified", "desc": "Electric cars as the default trajectory, not a niche.", "benchmark": "XLY"},
    {"year": 2023, "name": "James Webb Space Telescope", "category": "space", "status": "verified", "desc": "A working observatory rewriting early-universe astronomy.", "benchmark": "ITA"},
    {"year": 2023, "name": "Ancient DNA Analysis", "category": "biotech", "status": "verified", "desc": "Genomes from remains as a historical instrument.", "benchmark": "XBI"},
    {"year": 2023, "name": "Battery Recycling", "category": "energy", "status": "verified", "desc": "Closing the loop on EV and grid battery materials.", "benchmark": "XLE"},
    # 2024
    {"year": 2024, "name": "AI for Everything", "category": "ai", "status": "verified", "desc": "Generative models and agents entering ordinary software.", "benchmark": "XLK"},
    {"year": 2024, "name": "Super-Efficient Solar Cells", "category": "energy", "status": "verified", "desc": "Tandem and perovskite cells pushing conversion efficiency.", "benchmark": "TAN"},
    {"year": 2024, "name": "Apple Vision Pro", "category": "consumer", "status": "verified", "desc": "A high-end spatial computer from Apple."},
    {"year": 2024, "name": "Weight-Loss Drugs", "category": "biotech", "status": "verified", "desc": "GLP-1 medicines reshaping obesity and adjacent diseases.", "benchmark": "XBI"},
    {"year": 2024, "name": "Enhanced Geothermal Systems", "category": "energy", "status": "verified", "desc": "Engineered geothermal beyond natural hydrothermal sites.", "benchmark": "XLE"},
    {"year": 2024, "name": "Chiplets", "category": "hardware", "status": "verified", "desc": "Disaggregating processors into packaged chiplets.", "benchmark": "SOXX"},
    {"year": 2024, "name": "The First Gene-Editing Treatment", "category": "biotech", "status": "verified", "desc": "Approved CRISPR therapy reaching patients.", "benchmark": "XBI"},
    {"year": 2024, "name": "Exascale Computers", "category": "hardware", "status": "verified", "desc": "Supercomputers crossing a quintillion operations per second.", "benchmark": "XLK"},
    {"year": 2024, "name": "Heat Pumps", "category": "energy", "status": "verified", "desc": "Electrified heating as a climate and consumer appliance story."},
    {"year": 2024, "name": "Twitter Killers", "category": "consumer", "status": "verified", "desc": "Alternatives competing for the public square after Twitter."},
    # 2025
    {"year": 2025, "name": "Small Language Models", "category": "ai", "status": "verified", "desc": "Capable models that run locally or cheaply.", "benchmark": "SOXX"},
    {"year": 2025, "name": "Vera C. Rubin Observatory", "category": "space", "status": "verified", "desc": "A survey telescope built to film the changing sky.", "benchmark": "ITA"},
    {"year": 2025, "name": "Long-Acting HIV Prevention", "category": "biotech", "status": "verified", "desc": "Infrequent dosing that could change HIV prevention.", "benchmark": "XBI"},
    {"year": 2025, "name": "Generative AI Search", "category": "ai", "status": "verified", "desc": "Answers instead of ten blue links.", "benchmark": "XLK"},
    {"year": 2025, "name": "Cattle Burping Remedies", "category": "energy", "status": "verified", "desc": "Feed additives that cut methane from cattle."},
    {"year": 2025, "name": "Cleaner Jet Fuel", "category": "energy", "status": "verified", "desc": "Sustainable aviation fuel at commercial blend levels.", "benchmark": "XLE"},
    {"year": 2025, "name": "Fast-Learning Robots", "category": "ai", "status": "verified", "desc": "Robots acquiring skills from less demonstration data."},
    {"year": 2025, "name": "Stem-Cell Treatments That Work", "category": "biotech", "status": "verified", "desc": "Stem-cell treatments crossing from hope to outcomes.", "benchmark": "XBI"},
    {"year": 2025, "name": "Robotaxis", "category": "industrial", "status": "verified", "desc": "Driverless ride-hailing leaving geofenced demos.", "benchmark": "XLY"},
    {"year": 2025, "name": "Green Steel", "category": "energy", "status": "verified", "desc": "Steelmaking that cuts coal-based emissions.", "benchmark": "XLE"},
    # 2026
    {"year": 2026, "name": "Hyperscale AI Data Centers", "category": "ai", "status": "verified", "published_on": "2026-01-12",
     "desc": "Campus-scale facilities built around training and serving frontier models, at a steep energy cost.",
     "url": "https://www.technologyreview.com/2026/01/12/1130697", "benchmark": "XLK"},
    {"year": 2026, "name": "Sodium-Ion Batteries", "category": "energy", "status": "verified", "published_on": "2026-01-12",
     "desc": "Salt-based storage aiming at cheaper, safer packs than lithium for EVs and the grid.",
     "url": "https://www.technologyreview.com/2026/01/12/1130697", "benchmark": "XLE"},
    {"year": 2026, "name": "Personalized Gene Editing", "category": "biotech", "status": "verified", "published_on": "2026-01-12",
     "desc": "Personalized base editing used as a one-patient therapy.",
     "url": "https://www.technologyreview.com/2026/01/12/1129999", "benchmark": "XBI"},
    {"year": 2026, "name": "AI Interpretability", "category": "ai", "status": "verified", "published_on": "2026-01-12",
     "desc": "Tools that try to explain why a neural net did what it did.",
     "url": "https://www.technologyreview.com/2026/01/12/1130697", "benchmark": "XLK"},
    {"year": 2026, "name": "Advanced Nuclear Reactors", "category": "energy", "status": "verified", "published_on": "2026-01-12",
     "desc": "Novel materials and compact designs meant to make nuclear safer and cheaper.",
     "url": "https://www.technologyreview.com/2026/01/12/1130697", "benchmark": "XLE"},
    {"year": 2026, "name": "Embryo Genetic Scoring", "category": "biotech", "status": "verified", "published_on": "2026-01-12",
     "desc": "Genetic tests sold as a way to rank embryos on traits, not only disease.",
     "url": "https://www.technologyreview.com/2026/01/12/1130697", "benchmark": "XBI"},
    {"year": 2026, "name": "AI Companion Agents", "category": "ai", "status": "verified", "published_on": "2026-01-12",
     "desc": "Chatbots used as intimate, always-on companions.",
     "url": "https://www.technologyreview.com/2026/01/12/1130697", "benchmark": "XLK"},
    {"year": 2026, "name": "Gene Restoration", "category": "biotech", "status": "verified", "published_on": "2026-01-12",
     "desc": "Reconstructing extinct or lost genetic sequences for conservation and research.",
     "url": "https://www.technologyreview.com/2026/01/12/1130697", "benchmark": "XBI"},
    {"year": 2026, "name": "Generative Coding", "category": "ai", "status": "verified", "published_on": "2026-01-12",
     "desc": "AI that writes a material share of production software.",
     "url": "https://www.technologyreview.com/2026/01/12/1130697", "benchmark": "XLK"},
    {"year": 2026, "name": "Commercial Space Stations", "category": "space", "status": "verified", "published_on": "2026-01-12",
     "desc": "Private orbital outposts intended to succeed the ISS.",
     "url": "https://www.technologyreview.com/2026/01/12/1130697", "benchmark": "ITA"},
]

# slug, confidence, ticker, role_note
MAPPINGS = [
    # Deep Learning 2013 — include Intel as a contemporaneous loser, not only NVIDIA
    ("2013-deep-learning", "direct", "NVDA", "Already the leading GPU vendor; researchers were adopting CUDA for neural nets by 2013."),
    ("2013-deep-learning", "direct", "GOOGL", "Google Brain was a named deep-learning effort before the 2013 list."),
    ("2013-deep-learning", "direct", "IBM", "Watson and later neuromorphic/AI bets were the public IBM story at the time."),
    ("2013-deep-learning", "exposed", "MSFT", "Enterprise software vendor building ML tooling; not a pure-play then."),
    ("2013-deep-learning", "exposed", "INTC", "Incumbent CPU vendor that tried to stay relevant to training workloads and lagged."),
    ("2013-deep-learning", "exposed", "BIDU", "Chinese search company with an early public deep-learning lab."),
    ("2013-ultra-efficient-solar-power", "direct", "FSLR", "Thin-film utility solar manufacturer operating at list time."),
    ("2013-ultra-efficient-solar-power", "direct", "CSIQ", "Module manufacturer exposed to efficiency and cost curves."),
    ("2013-ultra-efficient-solar-power", "exposed", "ENPH", "Microinverters; downstream of panel efficiency rather than cell physics."),
    ("2013-temporary-social-media", "direct", "SNAP", "Snapchat is the product MIT was pointing at; IPO was later so returns start at IPO."),
    ("2013-temporary-social-media", "exposed", "META", "Incumbent social network that copied Stories; included as exposed, not the originator."),
    ("2013-smart-watches", "direct", "GRMN", "Shipped consumer smartwatches before Apple Watch."),
    ("2013-smart-watches", "direct", "FIT", "Wearable specialist later acquired by Alphabet — kept at exit to avoid survivorship bias."),
    ("2013-smart-watches", "exposed", "AAPL", "Apple Watch shipped in 2015; included as the firm that made the category mass-market."),
    ("2014-agricultural-drones", "direct", "DE", "John Deere was already buying precision-ag and later drone/see-and-spray capabilities. DJI is private."),
    ("2014-agricultural-drones", "exposed", "HON", "Industrial automation and aerospace sensors; indirect."),
    ("2014-neuromorphic-chips", "direct", "IBM", "TrueNorth was the named IBM neuromorphic project of that era."),
    ("2014-neuromorphic-chips", "direct", "INTC", "Loihi research chips; commercial impact stayed limited."),
    ("2014-neuromorphic-chips", "exposed", "NVDA", "Won the adjacent AI-silicon market with GPUs, not neuromorphic designs."),
    ("2014-genome-editing", "direct", "CRSP", "CRISPR therapeutics company; IPO 2016 so window starts then."),
    ("2014-genome-editing", "direct", "EDIT", "Editas was an early CRISPR name."),
    ("2014-genome-editing", "direct", "NTLA", "Intellia, another first-wave CRISPR company."),
    ("2014-genome-editing", "exposed", "VRTX", "Large biotech that later partnered on CRISPR medicines; not a CRISPR startup."),
    ("2014-oculus-rift", "direct", "META", "Bought Oculus in 2014; this is the public-market vehicle for that bet."),
    ("2014-oculus-rift", "exposed", "AAPL", "Later shipped Vision Pro; not a 2014 VR incumbent."),
    ("2014-oculus-rift", "exposed", "SNAP", "Spectacles / AR camera glasses; adjacent hardware, not Oculus."),
    ("2014-smart-wind-and-solar-power", "direct", "FSLR", "Utility solar operator/manufacturer whose value depends on dispatchable renewables."),
    ("2014-smart-wind-and-solar-power", "direct", "ENPH", "Inverters and energy management software."),
    ("2014-smart-wind-and-solar-power", "exposed", "RUN", "Residential solar installer; demand-side of 'smart' solar."),
    ("2015-magic-leap", "exposed", "META", "Magic Leap stayed private and struggled; Meta is the public AR/VR analog, not the named company."),
    ("2015-magic-leap", "exposed", "SNAP", "Consumer AR glasses; a weak proxy and labelled exposed on purpose."),
    ("2015-project-loon", "direct", "GOOGL", "Loon was an Alphabet X project, later shut down — the parent is the listed vehicle."),
    ("2015-liquid-biopsy", "direct", "GH", "Guardant is a named liquid-biopsy company (IPO 2018)."),
    ("2015-liquid-biopsy", "direct", "EXAS", "Cologuard / cancer screening from blood and stool."),
    ("2015-liquid-biopsy", "direct", "NTRA", "Cell-free DNA testing company."),
    ("2015-liquid-biopsy", "exposed", "ILMN", "Sequencing picks-and-shovels rather than a biopsy product."),
    ("2015-apple-pay", "direct", "AAPL", "The named product."),
    ("2015-apple-pay", "exposed", "V", "Card networks capture volume if tap-to-pay wins."),
    ("2015-apple-pay", "exposed", "MA", "Same network exposure as Visa."),
    ("2015-internet-of-dna", "direct", "ILMN", "Sequencing hardware and data platforms sit under shared genomic databases."),
    ("2016-conversational-interfaces", "direct", "AMZN", "Alexa was the breakout consumer assistant of that moment."),
    ("2016-conversational-interfaces", "direct", "GOOGL", "Google Assistant / Home."),
    ("2016-conversational-interfaces", "exposed", "AAPL", "Siri existed; less commercially central in 2016."),
    ("2016-conversational-interfaces", "exposed", "MSFT", "Cortana was a live bet that did not become the interface."),
    ("2016-reusable-rockets", "direct", "BA", "Legacy launch competitor; SpaceX is private so Boeing is a listed, often losing, analog."),
    ("2016-reusable-rockets", "exposed", "LMT", "Launch and space systems; not a reusable-booster specialist."),
    ("2016-reusable-rockets", "exposed", "RKLB", "Public small-launch company (IPO 2021); not SpaceX and not 2016-listed."),
    ("2016-solarcitys-gigafactory", "direct", "TSLA", "Tesla acquired SolarCity in 2016; the factory bet sits on this ticker."),
    ("2016-slack", "direct", "WORK", "Slack itself; delisted at the Salesforce deal so the score keeps the exit."),
    ("2016-slack", "exposed", "MSFT", "Teams is the incumbent response, not the MIT subject."),
    ("2016-slack", "exposed", "CRM", "Acquirer; holds Slack after July 2021."),
    ("2016-tesla-autopilot", "direct", "TSLA", "The named product."),
    ("2016-tesla-autopilot", "exposed", "GM", "Super Cruise / Cruise — a real contemporaneous ADAS effort, including later setbacks."),
    ("2016-tesla-autopilot", "exposed", "MBLY", "Mobileye (re-IPO 2022) sold the vision stack many OEMs used."),
    ("2017-self-driving-trucks", "exposed", "TSLA", "Semi and autonomy narrative; not a trucking-autonomy pure play."),
    ("2017-self-driving-trucks", "exposed", "GM", "Cruise attempted broader autonomy and retrenched."),
    ("2017-practical-quantum-computers", "direct", "IBM", "Public cloud quantum program running at list time."),
    ("2017-practical-quantum-computers", "direct", "GOOGL", "Hardware quantum effort that later claimed supremacy."),
    ("2017-practical-quantum-computers", "exposed", "IONQ", "Pure-play, but listed years later — window starts at IPO."),
    ("2017-practical-quantum-computers", "exposed", "RGTI", "Same caveat as IonQ."),
    ("2017-gene-therapy-2-0", "direct", "SRPT", "Commercial gene-therapy franchise."),
    ("2017-gene-therapy-2-0", "direct", "BMRN", "Early commercial gene-therapy company."),
    ("2017-gene-therapy-2-0", "exposed", "VRTX", "Large biotech with genetic-disease drugs, not classic gene therapy."),
    ("2017-reinforcement-learning", "direct", "GOOGL", "DeepMind's RL results were the public proof point."),
    ("2017-reinforcement-learning", "exposed", "NVDA", "Sells the compute RL consumes."),
    ("2017-reinforcement-learning", "exposed", "MSFT", "Cloud and later OpenAI; not an RL lab in 2017."),
    ("2017-reinforcement-learning", "exposed", "TSLA", "Autonomy framed as a learning-from-fleet problem."),
    ("2018-3-d-metal-printing", "direct", "DDD", "Incumbent additive manufacturer."),
    ("2018-3-d-metal-printing", "direct", "SSYS", "Incumbent additive manufacturer."),
    ("2018-3-d-metal-printing", "exposed", "HON", "Aerospace manufacturer that uses and supplies additive parts."),
    ("2018-ai-for-everybody", "direct", "MSFT", "Azure cognitive APIs and later OpenAI distribution."),
    ("2018-ai-for-everybody", "direct", "GOOGL", "Cloud AI APIs and TensorFlow."),
    ("2018-ai-for-everybody", "direct", "AMZN", "AWS ML services."),
    ("2018-ai-for-everybody", "exposed", "CRM", "Enterprise apps embedding AI, not a model lab."),
    ("2018-dueling-neural-networks", "direct", "NVDA", "GANs were a GPU-heavy research workload."),
    ("2018-dueling-neural-networks", "exposed", "ADBE", "Creative software that later shipped Firefly; not a 2018 GAN company."),
    ("2018-dueling-neural-networks", "exposed", "META", "Published GAN research; not a product GAN company then."),
    ("2018-genetic-fortune-telling", "direct", "ILMN", "Sequencing is the input to polygenic scores."),
    ("2018-genetic-fortune-telling", "exposed", "NTRA", "Sells genetic tests; not a consumer trait-score app."),
    ("2019-new-wave-nuclear-power", "direct", "BWXT", "Nuclear components and naval reactors — listed at the time."),
    ("2019-new-wave-nuclear-power", "exposed", "SMR", "NuScale listed later via SPAC; window starts at listing."),
    ("2019-new-wave-nuclear-power", "exposed", "OKLO", "Advanced-reactor SPAC; listed later."),
    ("2019-new-wave-nuclear-power", "exposed", "CEG", "Largest US nuclear operator, spun 2022."),
    ("2019-the-cow-free-burger", "direct", "BYND", "The public plant-meat vehicle. Impossible Foods is private."),
    ("2019-the-cow-free-burger", "exposed", "TSN", "Incumbent meatpacker that invested in alternatives."),
    ("2019-an-ecg-on-your-wrist", "direct", "AAPL", "Watch ECG was the consumer product MIT meant."),
    ("2019-an-ecg-on-your-wrist", "direct", "IRTC", "Medical-grade ambulatory ECG patch company."),
    ("2019-smooth-talking-ai-assistants", "direct", "GOOGL", "Duplex was the contemporaneous demo."),
    ("2019-smooth-talking-ai-assistants", "direct", "AMZN", "Alexa installed base."),
    ("2019-smooth-talking-ai-assistants", "exposed", "MSFT", "Voice in Office / later Copilot."),
    ("2020-digital-money", "direct", "PYPL", "Consumer digital wallet at list time."),
    ("2020-digital-money", "direct", "XYZ", "Cash App / bitcoin services (Block)."),
    ("2020-digital-money", "exposed", "COIN", "Crypto exchange IPO 2021."),
    ("2020-digital-money", "exposed", "MSTR", "Corporate bitcoin proxy, not a payments rail."),
    ("2020-satellite-mega-constellations", "direct", "IRDM", "Existing satellite communications operator."),
    ("2020-satellite-mega-constellations", "exposed", "ASTS", "Direct-to-cell constellation, listed later. SpaceX/Starlink is private."),
    ("2020-satellite-mega-constellations", "exposed", "RKLB", "Launch provider to constellation customers."),
    ("2020-quantum-supremacy", "direct", "GOOGL", "Google's Sycamore claim is the event MIT was naming."),
    ("2020-quantum-supremacy", "direct", "IBM", "Public counter-program and cloud access."),
    ("2020-quantum-supremacy", "exposed", "IONQ", "Listed later."),
    ("2020-tiny-ai", "direct", "NVDA", "Jetson / embedded inference."),
    ("2020-tiny-ai", "direct", "AAPL", "On-device neural engines in phones."),
    ("2020-tiny-ai", "exposed", "QCOM", "Wait - QCOM not in companies. skip"),
    ("2020-tiny-ai", "exposed", "AMD", "Edge and PC inference silicon."),
    ("2021-messenger-rna-vaccines", "direct", "MRNA", "Named mRNA platform company."),
    ("2021-messenger-rna-vaccines", "direct", "BNTX", "Pfizer partner; mRNA specialist."),
    ("2021-messenger-rna-vaccines", "direct", "PFE", "Commercial partner/distributor of BNT162b2."),
    ("2021-messenger-rna-vaccines", "exposed", "NVAX", "Protein-subunit COVID vaccine — related immunization, not mRNA."),
    ("2021-gpt-3", "direct", "MSFT", "Exclusive cloud partner to OpenAI by 2020-21."),
    ("2021-gpt-3", "exposed", "GOOGL", "Competing large-model lab (Google Brain / DeepMind)."),
    ("2021-gpt-3", "exposed", "NVDA", "Picks and shovels for training GPT-class models."),
    ("2021-gpt-3", "exposed", "AMZN", "AWS competitor in the same cloud AI race."),
    ("2021-lithium-metal-batteries", "direct", "QS", "Lithium-metal solid-state developer; listed around this period."),
    ("2021-lithium-metal-batteries", "exposed", "TSLA", "Largest EV battery buyer; not a lithium-metal specialist."),
    ("2021-lithium-metal-batteries", "exposed", "ALB", "Lithium supplier; commodity exposure, not cell design."),
    ("2021-green-hydrogen", "direct", "PLUG", "Public hydrogen fuel-cell and electrolyzer name."),
    ("2021-green-hydrogen", "direct", "BE", "Solid-oxide fuel cells / hydrogen-capable systems."),
    ("2021-green-hydrogen", "exposed", "APD", "Industrial gas incumbent that can supply hydrogen."),
    ("2021-remote-everything", "direct", "MSFT", "Teams / Azure as the WFH stack."),
    ("2021-remote-everything", "exposed", "CRM", "Cloud software that benefits if work stays distributed."),
    ("2021-remote-everything", "exposed", "NOW", "Workflow software for distributed enterprises."),
    ("2022-the-end-of-passwords", "direct", "OKTA", "Identity vendor whose business is replacing passwords."),
    ("2022-the-end-of-passwords", "exposed", "MSFT", "Windows Hello / Entra passkeys at OS scale."),
    ("2022-the-end-of-passwords", "exposed", "AAPL", "Passkeys in iOS / Safari."),
    ("2022-long-lasting-grid-batteries", "direct", "FLNC", "Grid storage integrator."),
    ("2022-long-lasting-grid-batteries", "direct", "TSLA", "Megapack is a named grid-battery product."),
    ("2022-long-lasting-grid-batteries", "exposed", "ENPH", "Mostly residential / commercial, not long-duration utility."),
    ("2022-ai-for-protein-folding", "direct", "SDGR", "Physics-plus-ML drug design company."),
    ("2022-ai-for-protein-folding", "direct", "RXRX", "Recursion uses ML on biology images and structures."),
    ("2022-ai-for-protein-folding", "exposed", "PFE", "Pharma buyer of the method, not AlphaFold."),
    ("2022-a-proof-of-stake", "direct", "COIN", "US exchange whose volumes track ETH and crypto activity."),
    ("2022-a-proof-of-stake", "exposed", "MSTR", "Bitcoin proxy — related digital-asset beta, not ETH staking."),
    ("2023-crispr-for-high-cholesterol", "direct", "NTLA", "In vivo CRISPR programs including cardiovascular."),
    ("2023-crispr-for-high-cholesterol", "direct", "CRSP", "CRISPR medicines including cardiovascular partnerships."),
    ("2023-crispr-for-high-cholesterol", "exposed", "VRTX", "Partner on CRISPR therapies (Casgevy) — not a cholesterol CRISPR name."),
    ("2023-crispr-for-high-cholesterol", "exposed", "REGN", "Antibody/genetic-medicine large cap with related cardiometabolic work."),
    ("2023-ai-that-makes-images", "direct", "MSFT", "DALL-E via OpenAI partnership / Copilot image."),
    ("2023-ai-that-makes-images", "direct", "GOOGL", "Imagen / Gemini image generation."),
    ("2023-ai-that-makes-images", "direct", "ADBE", "Firefly is a commercial image-gen product on this ticker."),
    ("2023-ai-that-makes-images", "exposed", "NVDA", "Training hardware."),
    ("2023-a-chip-design-that-changes-everything", "direct", "NVDA", "The architecture shift investors actually paid for was accelerated computing."),
    ("2023-a-chip-design-that-changes-everything", "direct", "AMD", "Chiplet-heavy CPUs/GPUs already shipping."),
    ("2023-a-chip-design-that-changes-everything", "exposed", "INTC", "Incumbent trying to catch the same design shift."),
    ("2023-a-chip-design-that-changes-everything", "exposed", "TSM", "Foundry that manufactures the new designs."),
    ("2023-the-inevitable-ev", "direct", "TSLA", "Category-defining EV maker."),
    ("2023-the-inevitable-ev", "direct", "RIVN", "Public EV startup — included so the cohort is not only the winner."),
    ("2023-the-inevitable-ev", "direct", "LCID", "Public EV startup with a harder path."),
    ("2023-the-inevitable-ev", "exposed", "GM", "Incumbent EV transition, including Cruise reversal."),
    ("2023-the-inevitable-ev", "exposed", "F", "Incumbent EV transition."),
    ("2023-battery-recycling", "exposed", "ALB", "Lithium producer; recycling is a competing/complementary source of units."),
    ("2023-battery-recycling", "exposed", "TSLA", "Operates recycling at Nevada; not a recycling pure play."),
    ("2024-ai-for-everything", "direct", "MSFT", "Copilot distributed across Office, GitHub, Azure."),
    ("2024-ai-for-everything", "direct", "GOOGL", "Gemini across search, cloud, Android."),
    ("2024-ai-for-everything", "direct", "NVDA", "Accelerators for the training/inference wave."),
    ("2024-ai-for-everything", "exposed", "META", "Open-weights Llama; ads business with AI spend."),
    ("2024-ai-for-everything", "exposed", "PLTR", "Enterprise AI applications, not a foundation-model lab."),
    ("2024-ai-for-everything", "exposed", "AMZN", "AWS Bedrock / Trainium."),
    ("2024-super-efficient-solar-cells", "direct", "FSLR", "CdTe modules; US utility solar."),
    ("2024-super-efficient-solar-cells", "direct", "ENPH", "Inverters attached to higher-efficiency arrays."),
    ("2024-super-efficient-solar-cells", "exposed", "SEDG", "Inverter peer; more cyclical than cell physics."),
    ("2024-weight-loss-drugs", "direct", "LLY", "Tirzepatide franchise."),
    ("2024-weight-loss-drugs", "direct", "NVO", "Semaglutide franchise."),
    ("2024-weight-loss-drugs", "exposed", "AMGN", "Obesity pipeline challenger."),
    ("2024-weight-loss-drugs", "exposed", "PFE", "Attempted oral obesity drugs; included as a contemporaneous large-pharma effort."),
    ("2024-chiplets", "direct", "AMD", "Shipped chiplet CPUs/GPUs years before the list."),
    ("2024-chiplets", "direct", "AVGO", "Custom accelerators and packaging."),
    ("2024-chiplets", "exposed", "TSM", "Advanced packaging / CoWoS constraint in the chiplet era."),
    ("2024-chiplets", "exposed", "INTC", "Foundry and tile strategy; execution mixed."),
    ("2024-the-first-gene-editing-treatment", "direct", "CRSP", "Casgevy co-developer."),
    ("2024-the-first-gene-editing-treatment", "direct", "VRTX", "Casgevy commercial partner."),
    ("2024-the-first-gene-editing-treatment", "exposed", "NTLA", "CRISPR peer, not the first approved therapy."),
    {"year_skip": True},
    ("2024-heat-pumps", "direct", "CARR", "Residential and commercial HVAC including heat pumps."),
    ("2024-heat-pumps", "direct", "TT", "Trane / climate systems."),
    ("2024-heat-pumps", "direct", "JCI", "Building efficiency and HVAC."),
    ("2024-apple-vision-pro", "direct", "AAPL", "The named product."),
    ("2024-apple-vision-pro", "exposed", "META", "Volume XR competitor (Quest)."),
    ("2025-generative-ai-search", "direct", "MSFT", "Bing / Copilot search."),
    ("2025-generative-ai-search", "direct", "GOOGL", "Incumbent search plus AI Overviews."),
    ("2025-generative-ai-search", "exposed", "META", "AI answers inside social surfaces."),
    ("2025-small-language-models", "direct", "AAPL", "On-device models as a product strategy."),
    ("2025-small-language-models", "direct", "MSFT", "Phi and on-device Copilot work."),
    ("2025-small-language-models", "exposed", "NVDA", "Still sells the GPUs even if models shrink."),
    ("2025-small-language-models", "exposed", "AMD", "PC and edge NPUs."),
    ("2025-robotaxis", "direct", "TSLA", "Robotaxi product claim on this ticker."),
    ("2025-robotaxis", "direct", "GOOGL", "Waymo is the operating robotaxi fleet inside Alphabet."),
    ("2025-robotaxis", "exposed", "GM", "Cruise was a real robotaxi attempt that was scaled back."),
    ("2025-robotaxis", "exposed", "AMZN", "Zoox; not yet a material earnings driver."),
    # 2026 watchlist
    ("2026-hyperscale-ai-data-centers", "direct", "NVDA", "Accelerators that fill the halls."),
    ("2026-hyperscale-ai-data-centers", "direct", "AMZN", "AWS is a hyperscale operator."),
    ("2026-hyperscale-ai-data-centers", "direct", "MSFT", "Azure is a hyperscale operator."),
    ("2026-hyperscale-ai-data-centers", "direct", "GOOGL", "Google Cloud / TPU campuses."),
    ("2026-hyperscale-ai-data-centers", "exposed", "EQIX", "Retail colocation; not a GPU campus builder but listed data-center real estate."),
    ("2026-hyperscale-ai-data-centers", "exposed", "DLR", "Wholesale data-center REIT."),
    ("2026-hyperscale-ai-data-centers", "exposed", "VRT", "Power and cooling gear for dense racks."),
    ("2026-hyperscale-ai-data-centers", "exposed", "CEG", "Nuclear-heavy generator selling power into AI load."),
    ("2026-advanced-nuclear-reactors", "direct", "BWXT", "Nuclear manufacturing incumbent."),
    ("2026-advanced-nuclear-reactors", "direct", "SMR", "NuScale small modular reactor developer."),
    ("2026-advanced-nuclear-reactors", "direct", "OKLO", "Advanced fission developer."),
    ("2026-advanced-nuclear-reactors", "exposed", "CEG", "Existing nuclear fleet that would compete with or host new designs."),
    ("2026-advanced-nuclear-reactors", "exposed", "GEV", "Hitachi-GE nuclear heritage via GE Vernova."),
    ("2026-advanced-nuclear-reactors", "exposed", "VST", "Merchant power, including nuclear, leveraged to AI load."),
    ("2026-embryo-genetic-scoring", "direct", "ILMN", "Sequencing used in embryo genetic tests."),
    ("2026-embryo-genetic-scoring", "exposed", "NTRA", "Reproductive genetic testing company."),
    ("2026-ai-companion-agents", "direct", "SNAP", "AR / chat products with companion-like bots."),
    ("2026-ai-companion-agents", "direct", "META", "Character-style AIs inside social apps."),
    ("2026-ai-companion-agents", "exposed", "GOOGL", "Assistant / Gemini as a companion surface."),
    ("2026-ai-companion-agents", "exposed", "MSFT", "Copilot as a work companion, not a social one."),
    ("2026-commercial-space-stations", "direct", "BA", "Heritage station contractor (Starliner / ISS)."),
    ("2026-commercial-space-stations", "exposed", "LMT", "Space systems prime."),
    ("2026-commercial-space-stations", "exposed", "NOC", "Space systems prime."),
    ("2026-commercial-space-stations", "exposed", "RKLB", "Launch and space-systems company that could serve stations."),
    ("2026-sodium-ion-batteries", "exposed", "ALB", "Lithium producer — sodium-ion is a competing chemistry, labelled exposed."),
    ("2026-sodium-ion-batteries", "exposed", "TSLA", "Battery buyer that could adopt or ignore sodium-ion."),
    ("2026-sodium-ion-batteries", "exposed", "QS", "Next-gen battery developer on a different chemistry."),
    ("2026-generative-coding", "direct", "MSFT", "GitHub Copilot is the named commercial product."),
    ("2026-generative-coding", "direct", "GOOGL", "Gemini / Cloud code assistants."),
    ("2026-generative-coding", "exposed", "GTLB", "Dev platform that embeds assistants; not the model provider."),
    ("2026-generative-coding", "exposed", "ANET", "Networking gear pulled by AI cluster buildout — weak mapping, exposed."),
    ("2026-personalized-gene-editing", "direct", "NTLA", "In vivo CRISPR/base-editing peer."),
    ("2026-personalized-gene-editing", "direct", "CRSP", "CRISPR medicines platform."),
    ("2026-personalized-gene-editing", "exposed", "VRTX", "Commercial CRISPR partner."),
    ("2026-ai-interpretability", "exposed", "GOOGL", "DeepMind publishes interpretability research."),
    ("2026-ai-interpretability", "exposed", "MSFT", "OpenAI-adjacent research distributed via Microsoft."),
    ("2026-ai-interpretability", "exposed", "META", "Open-weights models make interpretability a product risk topic."),
    ("2026-gene-restoration", "exposed", "ILMN", "Sequencing is the measurement layer; Colossal etc. are private."),
    ("2026-gene-restoration", "exposed", "CRSP", "Gene-editing tools that such projects would use."),
]

# Remove the accidental dict in MAPPINGS
MAPPINGS = [m for m in MAPPINGS if isinstance(m, tuple) and m[2] != "QCOM"]

ANALOGIES = [
    ("2026-hyperscale-ai-data-centers", "2013-deep-learning", "Same trade: the picks-and-shovels of an AI compute wave."),
    ("2026-hyperscale-ai-data-centers", "2021-gpt-3", "Language-model demand showing up as capex in clouds and chips."),
    ("2026-advanced-nuclear-reactors", "2019-new-wave-nuclear-power", "Earlier MIT nuclear-revival cohort."),
    ("2026-sodium-ion-batteries", "2021-lithium-metal-batteries", "Previous 'better battery chemistry' cohort — high dispersion, many zeros."),
    ("2026-sodium-ion-batteries", "2022-long-lasting-grid-batteries", "Grid-storage demand is the overlapping end market."),
    ("2026-generative-coding", "2021-gpt-3", "LLM capability showing up inside developer tools."),
    ("2026-generative-coding", "2018-ai-for-everybody", "Cloud AI APIs as the prior 'software will embed models' call."),
    ("2026-ai-companion-agents", "2016-conversational-interfaces", "Previous consumer-assistant cohort (Alexa/Google/Siri)."),
    ("2026-ai-companion-agents", "2019-smooth-talking-ai-assistants", "Voice agents that hold a conversation — mixed commercial follow-through."),
    ("2026-commercial-space-stations", "2016-reusable-rockets", "Launch cost is the gating input; SpaceX remains private in both eras."),
    ("2026-commercial-space-stations", "2020-satellite-mega-constellations", "Commercial space infrastructure listed names, with Starlink private."),
    ("2026-personalized-gene-editing", "2014-genome-editing", "First CRISPR cohort — long duration, high dispersion."),
    ("2026-personalized-gene-editing", "2024-the-first-gene-editing-treatment", "Approved CRISPR therapy as the nearest commercial analog."),
    ("2026-embryo-genetic-scoring", "2018-genetic-fortune-telling", "Polygenic scoring leaving the lab into consumer/clinic products."),
    ("2026-ai-interpretability", "2013-deep-learning", "Research-heavy AI category where listed exposure is the labs' parents."),
    ("2026-gene-restoration", "2023-ancient-dna-analysis", "Reading old genomes versus writing them back."),
]

# Old seed slugs → current slugs so MySQL rows keep their IDs and mappings.
SLUG_ALIASES = {
    "2001-brain-machine-interfaces": "2001-brain-machine-interface",
    "2004-rnai-therapy": "2004-rnai-interference",
    "2021-data-trust": "2021-data-trusts",
    "2022-a-pill-for-covid": "2022-covid-pill",
    "2022-proof-of-stake": "2022-a-proof-of-stake",
    "2022-a-long-lasting-grid-battery": "2022-long-lasting-grid-batteries",
    "2022-a-carbon-removal-factory": "2022-carbon-removal-factory",
    "2025-robots-that-learn-fast": "2025-fast-learning-robots",
    "2025-long-acting-hiv-prevention-medication": "2025-long-acting-hiv-prevention",
    "2025-effective-stem-cell-therapies": "2025-stem-cell-treatments-that-work",
    "2026-next-gen-nuclear": "2026-advanced-nuclear-reactors",
    "2026-embryo-scoring": "2026-embryo-genetic-scoring",
    "2026-ai-companions": "2026-ai-companion-agents",
    "2026-base-edited-baby": "2026-personalized-gene-editing",
    "2026-mechanistic-interpretability": "2026-ai-interpretability",
    "2026-gene-resurrection": "2026-gene-restoration",
}


def slug_for(year: int, name: str) -> str:
    import re
    s = name.lower().replace("'", "").replace("'", "")
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return f"{year}-{s}"
